# ===============================================
# CONFIGURACION DE LA BASE DE DATOS (PostgreSQL - NeonDB)
# ===============================================

spring.datasource.url=jdbc:postgresql://ep-nameless-night-ad3n1ho3-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QmMnT2uUrA3G
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================================
# CONFIGURACION DE EMAIL (Gmail SMTP)
# ===============================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password_here
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true